SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `db_transaction_node21`.`tb_ccb_order_bill`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `trade_time` datetime NULL DEFAULT NULL COMMENT '交易时间',
  `book_date` datetime NULL DEFAULT NULL COMMENT '记账日期, yyyymmdd',
  `bank_serial_number` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '银行流水号',
  `merchant_serial_number` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商户流水号',
  `out_trade_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '商户订单号',
  `trade_state` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '订单状态, 成功',
  `payer_account` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '付款方账号/客户号',
  `payer_name` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '付款方户名',
  `order_amount` decimal(11, 2) NULL DEFAULT NULL COMMENT '订单金额',
  `trans_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '交易金额',
  `service_charge` decimal(11, 2) NULL DEFAULT NULL COMMENT '手续费',
  `balance_amount` decimal(11, 2) NULL DEFAULT NULL COMMENT '结算金额',
  `pos_code` varchar(9) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '柜台代码',
  `pay_channel_name` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '发卡行/通道',
  `pay_card_type` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '支付卡种',
  `trans_type` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易类型',
  `stage_number` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '期数',
  `authorize_number` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '授权号',
  `project_number` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '项目号',
  `basic_account` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '基本户',
  `remark_one` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '备注一',
  `remark_two` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '备注二',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '最后更新时间',
  `comment` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '说明',
  `creator` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '创建人',
  `last_modified_by` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '最后修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `UNIQUE1`(`out_trade_no`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = COMPACT;

CREATE TABLE `db_transaction_node21`.`tb_htbe_pay_order_bill`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `account_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '账户id',
  `order_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '红塔银行订单号',
  `order_date` datetime NULL DEFAULT NULL COMMENT '订单日期',
  `ori_order_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '红塔银行原交易订单号，当前交易为退款交易时，有此参数',
  `mer_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '红塔银行一级商户号',
  `sec_mer_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '红塔银行二级商户号',
  `trans_amt` decimal(11, 2) NULL DEFAULT NULL COMMENT '订单总金额',
  `outer_order_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '商户平台订单号(我方订单号)',
  `curr` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '币种',
  `trans_stat` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '交易状态：0.成功 1.失败，2.未支付 3.处理中 4.已支付等待收货确认',
  `trans_type` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '交易类型,01 支付  09 退款',
  `mer_fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '平台手续费',
  `sec_mer_fee_charge` decimal(11, 2) NULL DEFAULT NULL COMMENT '二级商户手续费',
  `stl_date` datetime NULL DEFAULT NULL COMMENT '结算日期',
  `stl_batch_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '结算批次号',
  `stl_flag` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '结算flag',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '最后更新时间',
  `comment` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '说明',
  `creator` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '创建人',
  `last_modified_by` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '最后修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `UNIQUE1`(`order_no`) USING BTREE,
  UNIQUE INDEX `UNIQUE2`(`outer_order_no`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `db_transaction_node21`.`tb_order_bill`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `pay_channel_flag` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `pay_service_provider` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '支付服务提供方',
  `pay_channel` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '支付方式,wx,Alipay',
  `trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '订单号',
  `account_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '账户id',
  `client_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收银台(客户端)id',
  `trans_desc` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易描述',
  `fee_type` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '货币类型,符合ISO 4217标准的三位字母代码,如CNY',
  `trans_total` decimal(11, 2) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT '交易总价',
  `amount_received` decimal(11, 2) NULL DEFAULT NULL COMMENT '实收金额,实际到账',
  `amount_liquidation` decimal(11, 2) NULL DEFAULT NULL COMMENT '实际清算金额',
  `fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '我方平台手续费',
  `mer_fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '第三方平台手续费',
  `fee_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '总手续费',
  `rate` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '费率',
  `mer_rate` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '第三方平台费率',
  `rate_total` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '总费率',
  `customer_pay_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '客户id,比如微信支付时,为客户openid',
  `trade_time` datetime NULL DEFAULT NULL COMMENT '交易时间,也是服务器时间',
  `trans_state` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易状态,0,交易成功,1,交易失败,2,处理中',
  `is_refund` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '是否退款,00,交易订单无退款,01,交易订单全额退款,02,交易订单部分退款,10,退款订单',
  `client_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收银台(客户端)订单号',
  `third_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '第三方订单号,比如微信支付时,为微信方的订单号',
  `refund_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '当is_refund=10时有效,对应退款的原交易订单号',
  `refund_client_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '当is_refund=10时有效,对应退款的原收银台(客户端)订单号',
  `client_trade_time` datetime NULL DEFAULT NULL COMMENT '收银台(客户端)时间',
  `third_trade_time` datetime NULL DEFAULT NULL COMMENT '第三方交易时间,比如微信支付时,为微信方的交易时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '最后更新时间',
  `comment` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '说明',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `UNIQUE1`(`trans_code`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = COMPACT;

CREATE TABLE `db_transaction_node21`.`tb_order_bill_error`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `pay_channel` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '支付方式,wx,Alipay',
  `account_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '账户id',
  `error_type` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '差错类型,surplus,lack,error',
  `trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '我方订单号',
  `old_trans_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '原交易金额',
  `new_trans_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '处理后交易金额',
  `old_is_refund` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '原交易类型,00,交易订单无退款,01,交易订单全额退款,02,交易订单部分退款,10,退款订单',
  `new_is_refund` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '处理后交易类型,00,交易订单无退款,01,交易订单全额退款,02,交易订单部分退款,10,退款订单',
  `old_trans_state` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '原交易状态,0,交易成功,1,交易失败,2,处理中',
  `new_trans_state` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '处理后交易状态,0,交易成功,1,交易失败,2,处理中',
  `old_third_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '原第三方订单号,比如微信支付时,为微信方的订单号',
  `new_third_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '处理后第三方订单号,比如微信支付时,为微信方的订单号',
  `old_refund_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '当is_refund=10时有效,原对应退款的原交易订单号',
  `new_refund_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '当is_refund=10时有效,处理后对应退款的原交易订单号',
  `trea_result` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '处理结果,0,未处理，1,处理成功,2，处理失败,3,处理中, 4,人工处理',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '最后更新时间',
  `comment` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '说明',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = COMPACT;

CREATE TABLE `db_transaction_node21`.`tb_order_bill_summary`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `trade_time_start` datetime NULL DEFAULT NULL COMMENT '交易时间段起始',
  `trade_time_end` datetime NULL DEFAULT NULL COMMENT '交易时间段结束',
  `pay_service_provider` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '支付服务提供方',
  `pay_channel` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '支付方式,wx,Alipay',
  `pay_channel_flag` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `account_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '账户id',
  `fee_type` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '货币类型,符合ISO 4217标准的三位字母代码,如CNY',
  `trans_number` decimal(11, 0) NULL DEFAULT NULL COMMENT '交易笔数',
  `trans_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '交易总价',
  `amount_received` decimal(11, 2) NULL DEFAULT NULL COMMENT '实收金额,实际到账',
  `amount_liquidation` decimal(11, 2) NULL DEFAULT NULL COMMENT '实际清算金额',
  `fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '我方平台手续费',
  `mer_fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '第三方平台手续费',
  `fee_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '总手续费',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '最后更新时间',
  `comment` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '说明',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = COMPACT;

CREATE TABLE `db_transaction_node21`.`tb_sub_trans_detail`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `sub_trans_code` int(11) NULL DEFAULT NULL COMMENT '排序号',
  `account_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '账户id',
  `trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '订单号',
  `client_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收银台(客户端)订单号',
  `com_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商品编码',
  `com_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品名称',
  `trans_number` decimal(11, 2) NULL DEFAULT NULL COMMENT '交易数量',
  `trans_price` decimal(11, 2) NULL DEFAULT NULL COMMENT '交易单价',
  `trans_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '交易价格小计',
  `trans_cost` decimal(11, 2) NULL DEFAULT NULL COMMENT '成本单价',
  `trans_cost_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '成本小计',
  `customer_pay` decimal(11, 2) NULL DEFAULT NULL COMMENT '实际客户支付单价,一般和交易单价相等',
  `customer_pay_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '实际客户支付小计,一般和交易价格小计相等',
  `com_unit` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品单位',
  `com_brand` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品品牌',
  `com_packing` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品包装（条/包）',
  `com_manufacturer` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品制造商',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '最后更新时间',
  `comment` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '说明',
  `creator` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '创建人',
  `last_modified_by` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '最后修改人',
  `combination_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '组合支付时的组合code,一般与第一条的trans_code相同',
  `is_refund` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '是否退款,00,交易订单无退款,01,交易订单全额退款,02,交易订单部分退款,10,退款订单',
  `refund_number` decimal(11, 2) NULL DEFAULT NULL COMMENT '退款数量',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_trans_code`(`trans_code`) USING BTREE,
  INDEX `idx_client`(`sub_trans_code`, `account_id`, `client_trans_code`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `db_transaction_node21`.`tb_tobacco_commodity_info`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `account_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '账户id',
  `com_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商品编码',
  `short_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商品短码',
  `com_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品名称',
  `com_unit` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品主单位',
  `com_number` double NULL DEFAULT NULL COMMENT '商品库存',
  `com_cat_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品分类id',
  `com_cat_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品分类名称',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = COMPACT;

CREATE TABLE `db_transaction_node21`.`tb_trans_detail`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '订单号',
  `account_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '账户id',
  `client_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收银台(客户端)id',
  `trans_desc` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易描述',
  `trans_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '交易总价',
  `customer_pay_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '实际客户支付总价',
  `trans_cost_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '成本总价',
  `fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '手续费',
  `pay_channel` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '支付渠道',
  `pay_channel_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '支付通道标识',
  `trans_pay_meth` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易方式,和pay_channel配合使用，比如当pay_channel为微信支付时:0,刷卡支付,1,公众号(静态二维码)支付',
  `customer_pay_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '客户id,比如微信支付时,为客户appid',
  `member_phone` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `client_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收银台(客户端)订单号',
  `third_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '第三方订单号,比如微信支付时,为微信方的订单号',
  `create_user_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '创建人的userName',
  `create_time` datetime NULL DEFAULT NULL COMMENT '交易时间,也是服务器时间',
  `trans_state` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易状态,0,交易成功,1,交易失败,2,处理中',
  `is_refund` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '是否退款,00,交易订单无退款,01,交易订单全额退款,02,交易订单部分退款,10,退款订单',
  `refund_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '当is_refund=10时有效,对应退款的原交易订单号',
  `refund_client_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '当is_refund=10时有效,对应退款的原收银台(客户端)订单号',
  `client_time` datetime NULL DEFAULT NULL COMMENT '收银台(客户端)时间',
  `third_time` datetime NULL DEFAULT NULL COMMENT '第三方交易时间,比如微信支付时,为微信方的交易时间',
  `other_info` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '其它信息,以json存储',
  `version_no` int(11) NULL DEFAULT 0,
  `update_time` datetime NOT NULL COMMENT '最后更新时间',
  `comment` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '说明',
  `creator` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '创建人',
  `last_modified_by` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '最后修改人',
  `combination_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '组合支付时的组合code,一般与第一条的trans_code相同',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `UNIQUE1`(`trans_code`) USING BTREE,
  INDEX `idx_account_id`(`account_id`) USING BTREE,
  INDEX `idx_client_id`(`client_id`) USING BTREE,
  INDEX `idx_client_trans_code`(`client_trans_code`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `db_transaction_node21`.`tb_transaction_excel`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '订单号',
  `com_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品名称',
  `com_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商品编码',
  `trans_price` decimal(11, 2) NULL DEFAULT NULL COMMENT '交易单价',
  `trans_cost` decimal(11, 2) NULL DEFAULT NULL COMMENT '成本单价',
  `trans_number` decimal(11, 0) NULL DEFAULT NULL COMMENT '交易数量',
  `fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '手续费',
  `customer_pay` decimal(11, 2) NULL DEFAULT NULL COMMENT '实际客户支付单价,一般和交易单价相等',
  `trans_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '交易价格小计',
  `trans_cost_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '成本小计',
  `customer_pay_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '实际客户支付小计,一般和交易价格小计相等',
  `create_time` datetime NULL DEFAULT NULL COMMENT '交易时间,也是服务器时间',
  `customer_pay_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '客户id,比如微信支付时,为客户appid',
  `client_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收银台(客户端)订单号',
  `trans_state` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易状态,0,交易成功,1,交易失败,2,处理中',
  `is_refund` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '是否退款',
  `trans_desc` varchar(250) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易描述',
  `pay_channel` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '支付渠道',
  `trans_pay_meth` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易方式,和pay_channel配合使用，比如当pay_channel为微信支付时:0,刷卡支付,1,公众号(静态二维码)支付',
  `third_trans_code` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '第三方订单号,比如微信支付时,为微信方的订单号',
  `client_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收银台(客户端)id',
  `create_user_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '创建人的userName',
  `client_time` datetime NULL DEFAULT NULL COMMENT '收银台(客户端)时间',
  `third_time` datetime NULL DEFAULT NULL COMMENT '第三方交易时间,比如微信支付时,为微信方的交易时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = COMPACT;

CREATE TABLE `db_transaction_node21`.`tb_union_pay_order_bill`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `trade_time` datetime NULL DEFAULT NULL COMMENT '交易时间',
  `app_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '微信公众号appid',
  `third_merchant_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '第三方商户号,如微信商户号',
  `union_merchant_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '银联平台分配的连锁商户号',
  `union_sub_merchant_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '银联平台分配的子商户号',
  `device_info` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '设备编号, 一般为我方收银台id',
  `union_transaction_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '银联平台订单号',
  `third_transaction_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '第三方订单号',
  `trans_code` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '商户订单号',
  `user_sign` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户标识, 如微信openid',
  `transaction_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易类型',
  `transaction_status` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易状态, 支付成功, 转入退款',
  `pay_bank_code` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '付款银行',
  `fee_type` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '货币种类',
  `order_amount` decimal(11, 2) NULL DEFAULT NULL COMMENT '总金额',
  `ent_red_packet_amount` decimal(11, 2) NULL DEFAULT NULL COMMENT '企业红包金额',
  `union_refund_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '银联平台退款单号',
  `refund_trans_code` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商户退款单号',
  `refund_order_amount` decimal(11, 2) NULL DEFAULT NULL COMMENT '退款金额',
  `refund_ent_red_amount` decimal(11, 2) NULL DEFAULT NULL COMMENT '企业红包退款金额',
  `refund_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '退款类型, ORIGINAL, 原路返回',
  `refund_status` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '退款状态, 退款成功',
  `body_info` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商品名称',
  `attach_info` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商户数据包',
  `fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '手续费, 单位元, 按笔算时保留2位小数, 按汇总算时保留6位小数退款时为负值',
  `fee_rate` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '费率, 如0.280%',
  `client_type` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '终端类型',
  `order_check_sign` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '对账标识',
  `store_number` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '门店编号',
  `shop_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商户名称',
  `cashier` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '收银员',
  `union_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '微信支付交易时为子商户ID，银联二维码交易时为银联交易主键',
  `free_recharge_amount` decimal(11, 2) NULL DEFAULT NULL COMMENT '免充值券金额',
  `trans_total` decimal(11, 2) NULL DEFAULT NULL COMMENT '实收金额, 实收金额=订单金额-免充值券金额',
  `balance_amount` decimal(11, 2) NULL DEFAULT NULL COMMENT '结算金额, 结算金额=实收金额-手续费',
  `extension_two` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '扩展字段二',
  `extension_three` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '扩展字段三',
  `extension_four` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '扩展字段四',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '最后更新时间',
  `comment` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '说明',
  `creator` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '创建人',
  `last_modified_by` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '最后修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `UNIQUE1`(`union_transaction_id`, `union_refund_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = COMPACT;

CREATE TABLE `db_transaction_node21`.`tb_weixin_order_bill`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `trade_time` datetime NULL DEFAULT NULL COMMENT '交易时间,交易的支付成功时间或发起退款成功时间',
  `appid` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '公众账号ID',
  `mch_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商户号',
  `sub_mch_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '子商户号',
  `device_info` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '设备号',
  `transaction_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '微信订单号',
  `out_trade_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '商户订单号',
  `openid` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '用户标识,微信openid',
  `trade_type` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易类型,JSAPI,NATIVE,APP,MWEB,MICROPAY,PAP',
  `trade_state` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '交易状态,SUCCESS,REFUND,REVOKED',
  `bank_type` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '付款银行类型,采用字符串类型的银行标识',
  `fee_type` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '货币类型,符合ISO 4217标准的三位字母代码,如CNY',
  `total_fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '订单总金额',
  `coupon_fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '代金券或立减优惠金额',
  `refund_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '微信退款订单号,为订单时为0',
  `out_refund_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商户退款单号,为订单时为0',
  `settlement_refund_fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '退款金额,该笔退款或撤销单的应结算金额,为订单时为0.00',
  `coupon_refund_fee` decimal(11, 2) NULL DEFAULT NULL COMMENT '代金券或立减优惠退款金额,为订单或没有充值券退款则为0.00',
  `refund_channe` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '退款类型,ORIGINAL,BALANCE',
  `refund_status` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '退款状态,SUCCES,FAIL,PROCESSING',
  `body` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商品名称,商品描述',
  `attach` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '商品数据包',
  `service_charge` decimal(11, 2) NULL DEFAULT NULL COMMENT '手续费',
  `rate` varchar(16) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '费率',
  `order_amount` decimal(11, 2) NULL DEFAULT NULL COMMENT '订单金额(开通免充值券后的结算对账单使用)',
  `application_refund_amount` decimal(11, 2) NULL DEFAULT NULL COMMENT '申请退款金额(开通免充值券后的结算对账单使用)',
  `rate_notes` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '费率备注(开通免充值券后的结算对账单使用)',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '最后更新时间',
  `comment` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '说明',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `UNIQUE1`(`transaction_id`, `refund_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = COMPACT;

CREATE TABLE `db_transaction_node21`.`tb_ynrcc_pay_order_bill`  (
  `id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '主键',
  `account_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '账户id',
  `order_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '省农信订单号',
  `trade_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '第三方订单号(我方订单号)',
  `trade_type` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '交易类型',
  `trade_channel` varchar(12) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '支付方式',
  `trade_amt` decimal(11, 2) NOT NULL COMMENT '交易金额',
  `trade_date` datetime NOT NULL COMMENT '交易日期',
  `trade_time` datetime NOT NULL COMMENT '交易时间',
  `serial_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '银联跟踪号',
  `auth_code` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '授权码',
  `car_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '卡号',
  `tem_no` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '终端号',
  `mcc_put_fee` decimal(11, 2) NOT NULL COMMENT '应收手续费',
  `mcc_get_fee` decimal(11, 2) NOT NULL COMMENT '应付手续费',
  `fee_Inst` decimal(11, 2) NOT NULL COMMENT '清算净额',
  `retrivl_ref` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '检索参考号',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_time` datetime NOT NULL COMMENT '最后更新时间',
  `comment` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '说明',
  `creator` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '创建人',
  `last_modified_by` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '最后修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_order_no`(`order_no`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

SET FOREIGN_KEY_CHECKS=1;
